FROM maven:3.6.3-openjdk-15

WORKDIR /usr/src

# copy other source files (keep in image)
COPY . /usr/src/

#RUN mvn clean package

#RUN cp /usr/src/target/*.jar /usr/src/target/app.jar

RUN cp /usr/src/*.jks /usr/src/target/dhruv_keystore.jks
RUN cp /usr/src/target/*.jar /usr/src/target/app.jar

CMD ["java", "-Duser.timezone=America/New_York", "java -cp app.jar EMAConsumer.Consumer"]