FROM openjdk:8-jdk-alpine

#RUN yum install maven -y

WORKDIR /usr/src

# copy other source files (keep in image)
COPY . /usr/src/

#RUN mvn clean package

RUN cp /usr/src/*.jar /usr/src/target/app.jar
RUN cp /usr/src/*.jks /usr/src/keystore.jks
#RUN cp /usr/src/ /usr/src/

#CMD ["java", "-Duser.timezone=America/New_York", "java -cp app.jar EMAConsumer.Consumer"]
CMD ["java", "-Duser.timezone=America/New_York", "java -cp MarketPrice_KPL.jar EMAConsumer.Consumer"]